version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "alice"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-fo5lchf2vdnw"
s3_prefix = "alice"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
