AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  StageName:
    Type: String
    Default: dev
Description: >
  gameinfo

Globals:
  Function:
    Timeout: 2

Resources:
  GameInfoAPI:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: !Ref StageName
  GameInfoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: gameinfo/
      Handler: main
      Runtime: go1.x
      Events:
        ExplicitApi:
          Type: HttpApi
          Properties:
            Path: /gameinfo
            Method: GET
            ApiId: !Ref GameInfoAPI
      Environment:
        Variables:
          IGDB_KEY: 94d188db051c43f57fdc38841ea2a931

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  GameInfoAPI:
    Description: "API Gateway endpoint URL for ${StageName} environment for Function"
    Value: !Sub "https://${GameInfoAPI}.execute-api.${AWS::Region}.amazonaws.com/${StageName}"
  GameInfoFunction:
    Description: "Lambda Function ARN"
    Value: !GetAtt GameInfoFunction.Arn
  GameInfoIamRole:
    Description: "Implicit IAM Role created for GameInfoFunction"
    Value: !GetAtt GameInfoFunctionRole.Arn
